grails-app/domain/com/mphrx/apiAutomation/DicrRunError.groovy
package com.mphrx.apiAutomation

import com.mongodb.BasicDBObject

class DicrRunError {

    static constraints = {
    }

    static mapping = {
        collection "dicrRunError"
    }

    static mapWith = "mongo"

    static belongsTo = [dicrRunResult:DicrRunResult]
    static embedded = ['comparisonError']

    String collectionName
    String countMismatchError
    List<ComparisonError> comparisonError
    Date dateCreated
}

grails-app/domain/com/mphrx/apiAutomation/DicrRunResult.groovy
package com.mphrx.apiAutomation

class DicrRunResult {

    static constraints = {
    }

    static mapping = {
        collection "dicrRunResult"
    }

    static mapWith = "mongo"

    static belongsTo = [dicrRun:DicrRun]
    static hasMany = [dicrRunErrors:DicrRunError]

    String testCaseName
    String result
    int collectionsCountInBaseEnvironment
    int collectionsCountInTestEnvironment
    int commonCollectionsCount
    List<String> collectionsInBaseButNotInTest
    List<String> collectionsInTestButNotInBase
    String error
    Date lastUpdated
    Date dateCreated

}

grails-app/controllers/com/mphrx/apiAutomation/DicrRunResultController.groovy
package com.mphrx.apiAutomation



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DicrRunResultController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond DicrRunResult.list(params), model:[dicrRunResultInstanceCount: DicrRunResult.count()]
    }

    def show(DicrRunResult dicrRunResultInstance) {
        respond dicrRunResultInstance
    }

    def create() {
        respond new DicrRunResult(params)
    }

    @Transactional
    def save(DicrRunResult dicrRunResultInstance) {
        if (dicrRunResultInstance == null) {
            notFound()
            return
        }

        if (dicrRunResultInstance.hasErrors()) {
            respond dicrRunResultInstance.errors, view:'create'
            return
        }

        dicrRunResultInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'dicrRunResult.label', default: 'DicrRunResult'), dicrRunResultInstance.id])
                redirect dicrRunResultInstance
            }
            '*' { respond dicrRunResultInstance, [status: CREATED] }
        }
    }

    def edit(DicrRunResult dicrRunResultInstance) {
        respond dicrRunResultInstance
    }

    @Transactional
    def update(DicrRunResult dicrRunResultInstance) {
        if (dicrRunResultInstance == null) {
            notFound()
            return
        }

        if (dicrRunResultInstance.hasErrors()) {
            respond dicrRunResultInstance.errors, view:'edit'
            return
        }

        dicrRunResultInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'DicrRunResult.label', default: 'DicrRunResult'), dicrRunResultInstance.id])
                redirect dicrRunResultInstance
            }
            '*'{ respond dicrRunResultInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(DicrRunResult dicrRunResultInstance) {

        if (dicrRunResultInstance == null) {
            notFound()
            return
        }

        dicrRunResultInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'DicrRunResult.label', default: 'DicrRunResult'), dicrRunResultInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'dicrRunResult.label', default: 'DicrRunResult'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/dicrRunResult/_form.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunResult" %>



<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'collectionsCountInBaseEnvironment', 'error')} required">
	<label for="collectionsCountInBaseEnvironment">
		<g:message code="dicrRunResult.collectionsCountInBaseEnvironment.label" default="Collections Count In Base Environment" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="collectionsCountInBaseEnvironment" type="number" value="${dicrRunResultInstance.collectionsCountInBaseEnvironment}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'collectionsCountInTestEnvironment', 'error')} required">
	<label for="collectionsCountInTestEnvironment">
		<g:message code="dicrRunResult.collectionsCountInTestEnvironment.label" default="Collections Count In Test Environment" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="collectionsCountInTestEnvironment" type="number" value="${dicrRunResultInstance.collectionsCountInTestEnvironment}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'collectionsInBaseButNotInTest', 'error')} ">
	<label for="collectionsInBaseButNotInTest">
		<g:message code="dicrRunResult.collectionsInBaseButNotInTest.label" default="Collections In Base But Not In Test" />
		
	</label>
	

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'collectionsInTestButNotInBase', 'error')} ">
	<label for="collectionsInTestButNotInBase">
		<g:message code="dicrRunResult.collectionsInTestButNotInBase.label" default="Collections In Test But Not In Base" />
		
	</label>
	

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'commonCollectionsCount', 'error')} required">
	<label for="commonCollectionsCount">
		<g:message code="dicrRunResult.commonCollectionsCount.label" default="Common Collections Count" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="commonCollectionsCount" type="number" value="${dicrRunResultInstance.commonCollectionsCount}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'dicrRun', 'error')} required">
	<label for="dicrRun">
		<g:message code="dicrRunResult.dicrRun.label" default="Dicr Run" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="dicrRun" name="dicrRun.id" from="${com.mphrx.apiAutomation.DicrRun.list()}" optionKey="id" required="" value="${dicrRunResultInstance?.dicrRun?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'dicrRunErrors', 'error')} ">
	<label for="dicrRunErrors">
		<g:message code="dicrRunResult.dicrRunErrors.label" default="Dicr Run Errors" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${dicrRunResultInstance?.dicrRunErrors?}" var="d">
    <li><g:link controller="dicrRunError" action="show" id="${d.id}">${d?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="dicrRunError" action="create" params="['dicrRunResult.id': dicrRunResultInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'dicrRunError.label', default: 'DicrRunError')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'error', 'error')} required">
	<label for="error">
		<g:message code="dicrRunResult.error.label" default="Error" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="error" required="" value="${dicrRunResultInstance?.error}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'result', 'error')} required">
	<label for="result">
		<g:message code="dicrRunResult.result.label" default="Result" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="result" required="" value="${dicrRunResultInstance?.result}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunResultInstance, field: 'testCaseName', 'error')} required">
	<label for="testCaseName">
		<g:message code="dicrRunResult.testCaseName.label" default="Test Case Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="testCaseName" required="" value="${dicrRunResultInstance?.testCaseName}"/>

</div>

grails-app/views/dicrRunResult/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunResult.label', default: 'DicrRunResult')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-dicrRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-dicrRunResult" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${dicrRunResultInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${dicrRunResultInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:dicrRunResultInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/dicrRunResult/edit.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunResult.label', default: 'DicrRunResult')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-dicrRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-dicrRunResult" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${dicrRunResultInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${dicrRunResultInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:dicrRunResultInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${dicrRunResultInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/dicrRunResult/index.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunResult.label', default: 'DicrRunResult')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-dicrRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-dicrRunResult" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="collectionsCountInBaseEnvironment" title="${message(code: 'dicrRunResult.collectionsCountInBaseEnvironment.label', default: 'Collections Count In Base Environment')}" />
					
						<g:sortableColumn property="collectionsCountInTestEnvironment" title="${message(code: 'dicrRunResult.collectionsCountInTestEnvironment.label', default: 'Collections Count In Test Environment')}" />
					
						<g:sortableColumn property="commonCollectionsCount" title="${message(code: 'dicrRunResult.commonCollectionsCount.label', default: 'Common Collections Count')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'dicrRunResult.dateCreated.label', default: 'Date Created')}" />
					
						<th><g:message code="dicrRunResult.dicrRun.label" default="Dicr Run" /></th>
					
						<g:sortableColumn property="error" title="${message(code: 'dicrRunResult.error.label', default: 'Error')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${dicrRunResultInstanceList}" status="i" var="dicrRunResultInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${dicrRunResultInstance.id}">${fieldValue(bean: dicrRunResultInstance, field: "collectionsCountInBaseEnvironment")}</g:link></td>
					
						<td>${fieldValue(bean: dicrRunResultInstance, field: "collectionsCountInTestEnvironment")}</td>
					
						<td>${fieldValue(bean: dicrRunResultInstance, field: "commonCollectionsCount")}</td>
					
						<td><g:formatDate date="${dicrRunResultInstance.dateCreated}" /></td>
					
						<td>${fieldValue(bean: dicrRunResultInstance, field: "dicrRun")}</td>
					
						<td>${fieldValue(bean: dicrRunResultInstance, field: "error")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${dicrRunResultInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/dicrRunResult/show.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunResult.label', default: 'Dicr Run Errors')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
		<link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/lib',file: 'codemirror.css')}" charset="utf-8">
		<link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/theme',file: 'tomorrow-night.css')}" charset="utf-8">
		<link rel="stylesheet" href="${resource(dir: 'css',file: 'main.css')}" charset="utf-8">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<link rel="stylesheet" href="/resources/demos/style.css">
		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<style>
		.CodeMirror {
			border: 1px solid #eee;
			min-height:500px;
		}
		</style>
	</head>
	<body>
	<a href="#list-dicrRunError" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
	<div class="nav" role="navigation">
		<ul>
			<li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			<li><g:link controller="dicrRun" action="index">Dicr Runs</g:link></li>
			<li><g:link controller="dicrRun" action="show" id="${dicrRunResultInstance.dicrRun.id}">Dicr Run Result</g:link>
			</li>
		</ul>
	</div>
	<div id="list-dicrRunError" class="content scaffold-list" role="main">
		<h1><g:message code="default.list.label" args="[entityName]" /></h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
		</g:if>
		<table>
			<thead>
			<tr>

				<g:sortableColumn property="id" title="${message(code: 'dicrRunError.id.label', default: 'ID')}" />

				<g:sortableColumn property="collectionName" title="${message(code: 'dicrRunError.collectionName.label', default: 'Collection Name')}" />

				<g:sortableColumn property="countMismatchError" title="${message(code: 'dicrRunError.countMismatchError.label', default: 'Count Mismatch Error')}" />

				<g:sortableColumn property="dateCreated" title="${message(code: 'dicrRunError.dateCreated.label', default: 'Date Created')}" />

				<g:sortableColumn property="ComparisonError" title="${message(code: 'dicrRunError.ComparisonError.label', default: 'Comparison Error')}" />

				%{--
                                        <th><g:message code="dicrRunError.dicrRunResults.label" default="Dicr Run Results" /></th>
                --}%

				%{--
                                        <g:sortableColumn property="lastUpdated" title="${message(code: 'dicrRunError.lastUpdated.label', default: 'Last Updated')}" />
                --}%

			</tr>
			</thead>
			<tbody>
				<g:each in="${dicrRunResultInstance.dicrRunErrors.sort({it.id})}" status="i" var="dicrRunErrorInstance">
				<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

					<td>${dicrRunErrorInstance.id}</td>


					<td><g:link action="show" id="${dicrRunErrorInstance.id}">${fieldValue(bean: dicrRunErrorInstance, field: "collectionName")}</g:link></td>

					<td>${fieldValue(bean: dicrRunErrorInstance, field: "countMismatchError")}</td>

					<td><g:formatDate date="${dicrRunErrorInstance.dateCreated}" /></td>

					<td>
						<g:each in="${dicrRunErrorInstance.comparisonError}" var="comparisonErrorInstance" status="index">
							<button onclick="showErrorMessage('${URLEncoder.encode(comparisonErrorInstance.errorText,'UTF-8').replace("+", "%20")}')" value="Show Error" name="btn_${index+1}" >Show Error ${index+1} </button>
							<button onclick="showJSONDifference(${comparisonErrorInstance.baseJSON},${comparisonErrorInstance.testJSON},this)" value="Show Diff" name="btn_${index+1}" >Show Diff ${index+1}</button>
						</g:each>
					</td>


					%{--
                                            <td>${fieldValue(bean: dicrRunErrorInstance, field: "dicrRunResults")}</td>
                    --}%

					%{--
                                            <td><g:formatDate date="${dicrRunErrorInstance.lastUpdated}" /></td>
                    --}%

				</tr>
			</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate total="${dicrRunErrorInstanceCount ?: 0}" />
		</div>
	</div>

	<header id="header">

		<div class="right">
			<span id="error-message" style="display:none;">Invalid JSON</span>
		</div>
	</header>


	</div>

	<!-- The Modal -->
	<div id="myModal">


	</div>

	<div id = "jsonDiff-modal" style="width: 0px;height: 0px;">

		<div class="json-diff-input" style="width:50%; height: 100%; float:left;">
			<textarea id="json-diff-left"></textarea>
		</div>
		<div class="json-diff-input" style="width:50%; height: 100%;float:left;">
			<textarea id="json-diff-right"></textarea>
		</div>
		<div style="clear:both;"></div>
	</div>

	<script src="${resource(dir: 'www/lib/fast-json-patch/dist/',file: 'json-patch-duplex.min.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/backbone-events-standalone/',file: 'backbone-events-standalone.min.js')}" charset="utf-8"></script>

	<script src="${resource(dir: 'www/lib/codemirror/lib/',file: 'codemirror.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/codemirror/lib/util/',file: 'formatting.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/codemirror/mode/javascript/',file: 'javascript.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/codemirror/addon/edit/',file: 'matchbrackets.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'js/',file: 'main.js')}" charset="utf-8"></script>

	<script type="text/javascript">
		function showJSONDifference(json1,json2,element){
			var cmLeft = $('.CodeMirror')[0].CodeMirror;
			var cmRight = $('.CodeMirror')[1].CodeMirror;

			cmLeft.setValue("");
			cmRight.setValue("");
			cmLeft.setValue(JSON.stringify(json1,null,4));
			cmRight.setValue(JSON.stringify(json2,null,4));

			$('#jsonDiff-modal').removeAttr('style');
			$('#jsonDiff-modal').dialog( {
				width: "90%",
				maxWidth: "768px",
				height:'580'
			});
			cmLeft.focus();
			cmLeft.setCursor({line: 0, ch: 1});
			cmLeft;
		}

		function showErrorMessage(error) {
			$( "#myModal" ).html("<pre></pre>")
			$( "#myModal pre" ).text(decodeURIComponent(error));
			$( "#myModal" ).dialog({width: "90%",
				maxWidth: "768px",
				height:'580'});
		}

	</script>
	</body>
</html>