grails-app/domain/com/mphrx/apiAutomation/ApiRun.groovy
package com.mphrx.apiAutomation

import java.util.concurrent.Executor

class ApiRun {

    static constraints = {

    }

    static mapping = {
        collection "apiRun"
    }

    static mapWith = "mongo"

    static hasMany = [apiRunResults:ApiRunResult]

    Date startTime
    Date endTime
    String executor
    String baseEnvironmentUrl
    String baseEnvironmentVersion
    String testEnvironmentUrl
    String testEnvironmentVersion
    Date dateCreated
    Date lastUpdated
    String runmode


}

grails-app/domain/com/mphrx/apiAutomation/ApiRunResult.groovy
package com.mphrx.apiAutomation

class ApiRunResult {

    static constraints = {

    }


    static mapping = {
        collection "apiRunResult"
        baseResponse type: 'text'
        testResponse type: 'text'
        error type: 'text'
    }

    static mapWith = "mongo"

    static belongsTo = [apiRun:ApiRun]

    String testCaseName
    String moduleName
    String api
    String payload
    String baseResponse
    String testResponse
    String baseResponseCode
    String testResonseCode
    String result
    String error
    Date lastUpdated
    Date dateCreated

}

grails-app/controllers/com/mphrx/apiAutomation/ApiRunController.groovy
package com.mphrx.apiAutomation



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ApiRunController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    static scaffold = true

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ApiRun.list(params), model:[apiRunInstanceCount: ApiRun.count()]
    }

    def show(ApiRun apiRunInstance) {

        Integer max = params.max?Integer.parseInt(params.max):10
        max = Math.min(max ?: 10, 100)

        Integer offset = params.offset?Integer.parseInt(params.offset):0;

        List<ApiRunResult> apiRunResultList = []
        if (params.query) {
            apiRunInstance?.apiRunResults?.each { ApiRunResult apiRunResult ->
                if (apiRunResult.moduleName.toLowerCase().indexOf(params.query.toLowerCase()) > -1) {
                    apiRunResultList.push(apiRunResult)
                }

            }
            apiRunInstance?.apiRunResults?.each { ApiRunResult apiRunResult ->
                if (apiRunResult.testCaseName.toLowerCase().indexOf(params.query.toLowerCase()) > -1) {
                    apiRunResultList.push(apiRunResult)
                }

            }
            apiRunInstance?.apiRunResults?.each { ApiRunResult apiRunResult ->
                if (apiRunResult.api.toLowerCase().indexOf(params.query.toLowerCase()) > -1) {
                    apiRunResultList.push(apiRunResult)
                }

            }

            apiRunInstance?.apiRunResults?.each { ApiRunResult apiRunResult ->
                if (apiRunResult.result.toLowerCase().indexOf(params.query.toLowerCase()) > -1) {
                    apiRunResultList.push(apiRunResult)
                }

            }

            apiRunInstance?.apiRunResults?.each { ApiRunResult apiRunResult ->
                if (apiRunResult.testcaseId.toLowerCase().equals(params.query.toLowerCase())) {
                    apiRunResultList.push(apiRunResult)
                }

            }

            apiRunInstance?.apiRunResults = []
            apiRunInstance?.apiRunResults = apiRunResultList
        }

        def apiRunResultInstanceCount = apiRunInstance?.apiRunResults?.size()

        apiRunInstance?.apiRunResults  = apiRunInstance?.apiRunResults?.sort{it.id}?.toList()?.subList(offset,Math.min(apiRunInstance?.apiRunResults?.size(),(offset+max)))

        respond apiRunInstance, model:[apiRunResultInstanceCount: apiRunResultInstanceCount] /*, model: [apiRunResultInstanceCount:apiRunResultInstanceCount]*/

    }


    def create() {
        respond new ApiRun(params)
    }

    @Transactional
    def save(ApiRun apiRunInstance) {
        if (apiRunInstance == null) {
            notFound()
            return
        }

        if (apiRunInstance.hasErrors()) {
            respond apiRunInstance.errors, view:'create'
            return
        }

        apiRunInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'apiRun.label', default: 'ApiRun'), apiRunInstance.id])
                redirect apiRunInstance
            }
            '*' { respond apiRunInstance, [status: CREATED] }
        }
    }

    def edit(ApiRun apiRunInstance) {
        respond apiRunInstance
    }

    @Transactional
    def update(ApiRun apiRunInstance) {
        if (apiRunInstance == null) {
            notFound()
            return
        }

        if (apiRunInstance.hasErrors()) {
            respond apiRunInstance.errors, view:'edit'
            return
        }

        apiRunInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ApiRun.label', default: 'ApiRun'), apiRunInstance.id])
                redirect apiRunInstance
            }
            '*'{ respond apiRunInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ApiRun apiRunInstance) {

        if (apiRunInstance == null) {
            notFound()
            return
        }

        apiRunInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ApiRun.label', default: 'ApiRun'), apiRunInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'apiRun.label', default: 'ApiRun'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/apiRun/_form.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRun" %>



<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'apiRunResults', 'error')} ">
	<label for="apiRunResults">
		<g:message code="apiRun.apiRunResults.label" default="Api Run Results" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${apiRunInstance?.apiRunResults?}" var="a">
    <li><g:link controller="apiRunResult" action="show" id="${a.id}">${a?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="apiRunResult" action="create" params="['apiRun.id': apiRunInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'apiRunResult.label', default: 'ApiRunResult')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'baseEnvironmentUrl', 'error')} required">
	<label for="baseEnvironmentUrl">
		<g:message code="apiRun.baseEnvironmentUrl.label" default="Base Environment Url" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="baseEnvironmentUrl" required="" value="${apiRunInstance?.baseEnvironmentUrl}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'baseEnvironmentVersion', 'error')} required">
	<label for="baseEnvironmentVersion">
		<g:message code="apiRun.baseEnvironmentVersion.label" default="Base Environment Version" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="baseEnvironmentVersion" required="" value="${apiRunInstance?.baseEnvironmentVersion}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'endTime', 'error')} required">
	<label for="endTime">
		<g:message code="apiRun.endTime.label" default="End Time" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="endTime" precision="day"  value="${apiRunInstance?.endTime}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'executor', 'error')} required">
	<label for="executor">
		<g:message code="apiRun.executor.label" default="Executor" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="executor" required="" value="${apiRunInstance?.executor}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'startTime', 'error')} required">
	<label for="startTime">
		<g:message code="apiRun.startTime.label" default="Start Time" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="startTime" precision="day"  value="${apiRunInstance?.startTime}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'testEnvironmentUrl', 'error')} required">
	<label for="testEnvironmentUrl">
		<g:message code="apiRun.testEnvironmentUrl.label" default="Test Environment Url" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="testEnvironmentUrl" required="" value="${apiRunInstance?.testEnvironmentUrl}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunInstance, field: 'testEnvironmentVersion', 'error')} required">
	<label for="testEnvironmentVersion">
		<g:message code="apiRun.testEnvironmentVersion.label" default="Test Environment Version" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="testEnvironmentVersion" required="" value="${apiRunInstance?.testEnvironmentVersion}"/>

</div>

grails-app/views/apiRun/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRun.label', default: 'ApiRun')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-apiRun" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-apiRun" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${apiRunInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${apiRunInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:apiRunInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/apiRun/edit.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRun" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRun.label', default: 'ApiRun')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-apiRun" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-apiRun" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${apiRunInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${apiRunInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:apiRunInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${apiRunInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/apiRun/index.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRun" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRun.label', default: 'API Runs')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-apiRun" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="list-apiRun" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<g:sortableColumn property="apiRunId" title="${message(code: 'apiRun.apiRunId.label', default: 'Run Id')}" />

						<g:sortableColumn property="baseEnvironmentUrl" title="${message(code: 'apiRun.baseEnvironmentUrl.label', default: 'Base Env Url')}" />
					
						<g:sortableColumn property="baseEnvironmentVersion" title="${message(code: 'apiRun.baseEnvironmentVersion.label', default: 'Base Env Version')}" />

						<g:sortableColumn property="testEnvironmentUrl" title="${message(code: 'apiRun.testEnvironmentUrl.label', default: 'Test Env Url')}" />

						<g:sortableColumn property="testEnvironmentVersion" title="${message(code: 'apiRun.testEnvironmentVersion.label', default: 'Test Env Version')}" />

%{--
						<g:sortableColumn property="executor" title="${message(code: 'apiRun.executor.label', default: 'Executor')}" />
--}%

						<g:sortableColumn property="startTime" title="${message(code: 'apiRun.startTime.label', default: 'Start Time')}" />

						<g:sortableColumn property="endTime" title="${message(code: 'apiRun.endTime.label', default: 'End Time')}" />

						<g:sortableColumn property="endTime" title="${message(code: 'apiRun.goToTestResults.label', default: 'Results')}" />

						%{--
                                                <g:sortableColumn property="dateCreated" title="${message(code: 'apiRun.dateCreated.label', default: 'Date Created')}" />
                        --}%



%{--
						<g:sortableColumn property="lastUpdated" title="${message(code: 'apiRun.lastUpdated.label', default: 'Last Updated')}" />
--}%

					</tr>
				</thead>
				<tbody>
				<g:each in="${apiRunInstanceList}" status="i" var="apiRunInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td>${fieldValue(bean: apiRunInstance, field: "id")}</td>

						<td>${fieldValue(bean: apiRunInstance, field: "baseEnvironmentUrl")}</td>
					
						<td>${fieldValue(bean: apiRunInstance, field: "baseEnvironmentVersion")}</td>

						<td>${fieldValue(bean: apiRunInstance, field: "testEnvironmentUrl")}</td>

						<td>${fieldValue(bean: apiRunInstance, field: "testEnvironmentVersion")}</td>

%{--
						<td>${fieldValue(bean: apiRunInstance, field: "executor")}</td>
--}%

						<td><g:formatDate date="${apiRunInstance.startTime}" /></td>
					
						<td><g:formatDate date="${apiRunInstance.endTime}" /></td>

						<td><g:link action="show" id="${apiRunInstance.id}">See Results</g:link></td>


					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${apiRunInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/apiRun/show.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRun" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'apiRun.label', default: 'API Test Run Results')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
	<link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/lib',file: 'codemirror.css')}" charset="utf-8">
	<link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/theme',file: 'tomorrow-night.css')}" charset="utf-8">
	<link rel="stylesheet" href="${resource(dir: 'css',file: 'main.css')}" charset="utf-8">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">


	<script src="${resource(dir:'jdd',file:'jquery-1.12.4.js')}"></script>
	<script src="${resource(dir:'jdd',file:'jquery-ui.js')}"></script>

	<script src="${resource(dir:'jdd',file:'underscore-min.js')}" type="text/javascript" charset="utf-8"></script>

	<link rel="stylesheet" href="${resource(dir:'jdd',file:'reset.css')}" type="text/css" media="screen">
	<link rel="stylesheet" href="${resource(dir:'jdd',file:'throbber.css')}" type="text/css" media="screen">
	<link rel="stylesheet" href="${resource(dir:'jdd',file:'jdd.css')}" type="text/css" media="screen">

	<script src="${resource(dir:'jdd/jsl',file:'jsl.format.js')}" type="text/javascript" charset="utf-8"></script>
	<script src="${resource(dir:'jdd/jsl',file:'jsl.parser.js')}" type="text/javascript" charset="utf-8"></script>
	<script src="${resource(dir:'jdd',file:'jdd.js')}" type="text/javascript" charset="utf-8"></script>

	<style>
	.CodeMirror {
		border: 1px solid #eee;
		min-height:500px;
	}
	</style>
</head>
<body>
<a href="#show-apiRun" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
	<ul>
		<li><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link action="index">API Runs</g:link></li>

	</ul>
</div>
<div id="show-apiRun" class="content scaffold-show" role="main">
	<h1><g:message code="default.show.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<fieldset class="form">
		<g:form name="searchForm" action="show" method="GET" id="${apiRunInstance.id}">
			<div class="fieldcontain">
				<g:textField name="query" value="${params.query}"/>
				<g:submitButton id="submitButton" name="Search" value="Search"></g:submitButton>
				<input type="button" onclick="clearFields()" value="Reset">
				Showing ${apiRunResultInstanceCount} results
			</div>

		</g:form>
	</fieldset>
	%{--			<div>

                </div>--}%


	<table width="100%" style="table-layout: fixed; width: 100%">
		<th width="10%">Test ID</th>
		<th width="22%">Test Case Name</th>
		<th width="15%" style="word-wrap: break-word">Module Name</th>
		<th width="25%" style="word-wrap: break-word">API</th>
		<th width="7%">Payload</th>
		<th width="7%">Result</th>
		<th width="7%">Error</th>
		<th width="7%">Compare Responses</th>


		<g:each in="${apiRunInstance.apiRunResults.sort({it.id})}" var="apiRunResult">
			<tr style="word-wrap: break-word">
				<td>${apiRunResult.testcaseId}</td>
				<td>${apiRunResult.testCaseName}</td>
				<td>${apiRunResult.moduleName}</td>
				<td style="word-wrap: break-word" width="30%">${apiRunResult.api}</td>

				<td><button style="height:40px;width:80px" onclick="showPayload('${apiRunResult.payload}')">Show Payload</button></td>
				<td >${apiRunResult.result}</td>

				<g:if test="${apiRunResult.error=="No Error"}">
					<td><button style="height:40px;width:80px" disabled="disabled"  onclick="showErrorMessage('${URLEncoder.encode(apiRunResult.error,'UTF-8').replace("+", "%20")}')"> No  Error </button></td>
				</g:if>
				<g:else>
					<td><button style="height:40px;width:80px" onclick="showErrorMessage('${URLEncoder.encode(apiRunResult.error,'UTF-8').replace("+", "%20")}')">Show Error</button></td>
				</g:else>

				<g:if test="${(apiRunResult.baseResponse as java.util.Map).size()>3 && (apiRunResult.testResponse as java.util.Map).size()>3}">
					<td><button style="height:40px;width:82px" onclick="showJSONDifference(${apiRunResult.baseResponse},${apiRunResult.testResponse})">Compare Responses</button></td>
				</g:if>
				<g:else>
					<td><button style="height:40px;width:82px" disabled="disabled" onclick="showJSONDifference(${apiRunResult.baseResponse},${apiRunResult.testResponse})">Nothing to Compare
					</button></td>
				</g:else>

			</tr>

		</g:each>
	</table>
	<div class="pagination">
		<g:paginate params="${[query:params.query]}" id="${apiRunInstance.id}" total="${apiRunResultInstanceCount ?: 0}" />
	</div>

	<header id="header">

		<div class="right">
			<span id="error-message" style="display:none;">Invalid JSON</span>
		</div>
	</header>


</div>

<!-- The Modal -->
<div id="myModal">


</div>

<div id="main" style="width: 0px;height: 0px;display: none;">
	<div class="initContainer">
		<div class="left">
			<textarea spellcheck="false" id="textarealeft" placeholder="Enter JSON to compare, enter an URL to JSON"></textarea>
			<pre id="errorLeft" class="error"></pre>
			<span class="fileInput">or <input type="file" id="fileLeft" onchange="jdd.handleFiles(this.files, 'left')"></span>
		</div>

		<div class="center">
			<button id="compare">Compare</button>
			<div class="throbber-loader"></div>
			<br/><br/><br/><br/>
			or try some <a href="#" id="sample">sample data</a>

		</div>

		<div class="right">
			<textarea spellcheck="false" class="right" id="textarearight" placeholder="Enter JSON to compare, enter an URL to JSON"></textarea>
			<pre id="errorRight" class="error"></pre>
			<span class="fileInput">or <input type="file" id="fileRight" onchange="jdd.handleFiles(this.files, 'right')"></span>
		</div>
	</div>

	<div class="diffcontainer">
		<div id="report">
		</div>
		<pre id="out" class="left" class="codeBlock"></pre>
		<pre id="out2" class="right" class="codeBlock"></pre>
		<ul id="toolbar" class="toolbar"></ul>
	</div>
</div>


<script src="${resource(dir: 'www/lib/fast-json-patch/dist/',file: 'json-patch-duplex.min.js')}" charset="utf-8"></script>
<script src="${resource(dir: 'www/lib/backbone-events-standalone/',file: 'backbone-events-standalone.min.js')}" charset="utf-8"></script>

<!-- Requires CodeMirror -->
<script type="text/javascript" src="${resource(dir: 'Mergely/lib',file: 'codemirror.js')}"></script>
<link type="text/css" rel="stylesheet" href="${resource(dir: 'Mergely/lib',file: 'codemirror.css')}" />

<!-- Requires Mergely -->
<script type="text/javascript" src="${resource(dir: 'Mergely/lib',file: 'mergely.js')}"></script>
<link type="text/css" rel="stylesheet" href="${resource(dir: 'Mergely/lib',file: 'mergely.css')}" />
<script src="${resource(dir: 'js/',file: 'main.js')}" charset="utf-8"></script>


<script type="text/javascript">
	function closeDialog(){
		$('#main').dialog('close');
	}

	function showJSONDifference(json1,json2){

		json1 = JSON.parse(JSON.stringify(json1).replace(/\\n/g,'!NEWLINE!'))
		json2 = JSON.parse(JSON.stringify(json2).replace(/\\n/g,'!NEWLINE!'))

			$('#textarealeft').val(JSON.stringify(json1,null,4));

			$('#textarealeft').val(JSON.stringify(json1,null,4).replace(/!NEWLINE!/g,'\\\\n'));

			$('#textarearight').val(JSON.stringify(json2,null,4).replace(/!NEWLINE!/g,'\\\\n'));

		try{
			jdd.compare();
		}catch (e){
			console.error(e)
			if($("#" + "message").length == 0) {
				$('#main').prepend("<div id='message' style='text-align: center;'><span style='color:red'>Please compare manually as tool is facing some issues with comparison. Please see console logs for details. </span></div>")
			}
		}

		$('#main').dialog({
			width: "82%",
			height: '650',
			resizable:false,
			left:'9%'
		});
	}

	function showErrorMessage(error) {
		$( "#myModal" ).html("<pre></pre>")
		$( "#myModal pre" ).text(decodeURIComponent(error));
		$( "#myModal" ).dialog({width: "90%",
			maxWidth: "768px",
			height:'580'});
	}

	function showPayload(payload) {
		payload=JSON.parse(payload)
		$( "#myModal" ).html("<pre></pre>")
		$( "#myModal pre" ).text(decodeURIComponent(JSON.stringify(payload,null,4)));
		$( "#myModal" ).dialog({width: "90%",
			maxWidth: "768px",
			height:'580'});
	}


	function clearFields() {
		document.getElementsByName("query")[0].value=""
		document.getElementById("submitButton").click()
	}

</script>
</body>
</html>