grails-app/domain/com/mphrx/apiAutomation/ApiRunResult.groovy
package com.mphrx.apiAutomation

class ApiRunResult {

    static constraints = {

    }


    static mapping = {
        collection "apiRunResult"
        baseResponse type: 'text'
        testResponse type: 'text'
        error type: 'text'
    }

    static mapWith = "mongo"

    static belongsTo = [apiRun:ApiRun]

    String testCaseName
    String moduleName
    String api
    String payload
    String baseResponse
    String testResponse
    String baseResponseCode
    String testResonseCode
    String result
    String error
    Date lastUpdated
    Date dateCreated

}

grails-app/controllers/com/mphrx/apiAutomation/ApiRunResultController.groovy
package com.mphrx.apiAutomation



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ApiRunResultController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]



    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ApiRunResult.list(params), model:[apiRunResultInstanceCount: ApiRunResult.count()]
    }

    def show(ApiRunResult apiRunResultInstance) {
        respond apiRunResultInstance
    }

    def create() {
        respond new ApiRunResult(params)
    }

    @Transactional
    def save(ApiRunResult apiRunResultInstance) {
        if (apiRunResultInstance == null) {
            notFound()
            return
        }

        if (apiRunResultInstance.hasErrors()) {
            respond apiRunResultInstance.errors, view:'create'
            return
        }

        apiRunResultInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'apiRunResult.label', default: 'ApiRunResult'), apiRunResultInstance.id])
                redirect apiRunResultInstance
            }
            '*' { respond apiRunResultInstance, [status: CREATED] }
        }
    }

    def edit(ApiRunResult apiRunResultInstance) {
        respond apiRunResultInstance
    }

    @Transactional
    def update(ApiRunResult apiRunResultInstance) {
        if (apiRunResultInstance == null) {
            notFound()
            return
        }

        if (apiRunResultInstance.hasErrors()) {
            respond apiRunResultInstance.errors, view:'edit'
            return
        }

        apiRunResultInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ApiRunResult.label', default: 'ApiRunResult'), apiRunResultInstance.id])
                redirect apiRunResultInstance
            }
            '*'{ respond apiRunResultInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ApiRunResult apiRunResultInstance) {

        if (apiRunResultInstance == null) {
            notFound()
            return
        }

        apiRunResultInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ApiRunResult.label', default: 'ApiRunResult'), apiRunResultInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'apiRunResult.label', default: 'ApiRunResult'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/apiRunResult/_form.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRunResult" %>



<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'api', 'error')} required">
	<label for="api">
		<g:message code="apiRunResult.api.label" default="Api" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="api" required="" value="${apiRunResultInstance?.api}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'apiRun', 'error')} required">
	<label for="apiRun">
		<g:message code="apiRunResult.apiRun.label" default="Api Run" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="apiRun" name="apiRun.id" from="${com.mphrx.apiAutomation.ApiRun.list()}" optionKey="id" required="" value="${apiRunResultInstance?.apiRun?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'baseResponse', 'error')} required">
	<label for="baseResponse">
		<g:message code="apiRunResult.baseResponse.label" default="Base Response" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="baseResponse" required="" value="${apiRunResultInstance?.baseResponse}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'baseResponseCode', 'error')} required">
	<label for="baseResponseCode">
		<g:message code="apiRunResult.baseResponseCode.label" default="Base Response Code" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="baseResponseCode" required="" value="${apiRunResultInstance?.baseResponseCode}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'error', 'error')} required">
	<label for="error">
		<g:message code="apiRunResult.error.label" default="Error" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="error" required="" value="${apiRunResultInstance?.error}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'moduleName', 'error')} required">
	<label for="moduleName">
		<g:message code="apiRunResult.moduleName.label" default="Module Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="moduleName" required="" value="${apiRunResultInstance?.moduleName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'payload', 'error')} required">
	<label for="payload">
		<g:message code="apiRunResult.payload.label" default="Payload" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="payload" required="" value="${apiRunResultInstance?.payload}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'result', 'error')} required">
	<label for="result">
		<g:message code="apiRunResult.result.label" default="Result" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="result" required="" value="${apiRunResultInstance?.result}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'testCaseName', 'error')} required">
	<label for="testCaseName">
		<g:message code="apiRunResult.testCaseName.label" default="Test Case Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="testCaseName" required="" value="${apiRunResultInstance?.testCaseName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'testResonseCode', 'error')} required">
	<label for="testResonseCode">
		<g:message code="apiRunResult.testResonseCode.label" default="Test Resonse Code" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="testResonseCode" required="" value="${apiRunResultInstance?.testResonseCode}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: apiRunResultInstance, field: 'testResponse', 'error')} required">
	<label for="testResponse">
		<g:message code="apiRunResult.testResponse.label" default="Test Response" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="testResponse" required="" value="${apiRunResultInstance?.testResponse}"/>

</div>

grails-app/views/apiRunResult/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRunResult.label', default: 'ApiRunResult')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-apiRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-apiRunResult" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${apiRunResultInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${apiRunResultInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:apiRunResultInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/apiRunResult/edit.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRunResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRunResult.label', default: 'ApiRunResult')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-apiRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-apiRunResult" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${apiRunResultInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${apiRunResultInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:apiRunResultInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${apiRunResultInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/apiRunResult/index.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRunResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRunResult.label', default: 'ApiRunResult')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
		<link rel="stylesheet" href="../online-json-diff-master/www/lib/codemirror/lib/codemirror.css" charset="utf-8">
		<link rel="stylesheet" href="../online-json-diff-master/www/lib/codemirror/theme/tomorrow-night.css" charset="utf-8">
		<link rel="stylesheet" href="../online-json-diff-master/css/main.css" charset="utf-8">

	</head>
	<body>
		<a href="#list-apiRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-apiRunResult" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="api" title="${message(code: 'apiRunResult.api.label', default: 'Api')}" />
					
						<th><g:message code="apiRunResult.apiRun.label" default="Api Run" /></th>
					
						<g:sortableColumn property="baseResponse" title="${message(code: 'apiRunResult.baseResponse.label', default: 'Base Response')}" />
					
						<g:sortableColumn property="baseResponseCode" title="${message(code: 'apiRunResult.baseResponseCode.label', default: 'Base Response Code')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'apiRunResult.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="error" title="${message(code: 'apiRunResult.error.label', default: 'Error')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${apiRunResultInstanceList}" status="i" var="apiRunResultInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${apiRunResultInstance.id}">${fieldValue(bean: apiRunResultInstance, field: "api")}</g:link></td>
					
						<td>${fieldValue(bean: apiRunResultInstance, field: "apiRun")}</td>
					
						<td>${fieldValue(bean: apiRunResultInstance, field: "baseResponse")}</td>
					
						<td>${fieldValue(bean: apiRunResultInstance, field: "baseResponseCode")}</td>
					
						<td><g:formatDate date="${apiRunResultInstance.dateCreated}" /></td>
					
						<td>${fieldValue(bean: apiRunResultInstance, field: "error")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${apiRunResultInstanceCount ?: 0}" />
			</div>
		</div>
	<script src="../online-json-diff-master/www/lib/fast-json-patch/dist/json-patch-duplex.min.js" charset="utf-8"></script>
	<script src="../online-json-diff-master/www/lib/backbone-events-standalone/backbone-events-standalone.min.js" charset="utf-8"></script>
	<script src="../online-json-diff-master/www/lib/codemirror/lib/codemirror.js" charset="utf-8"></script>
	<script src="../online-json-diff-master/www/lib/codemirror/lib/util/formatting.js" charset="utf-8"></script>
	<script src="../online-json-diff-master/www/lib/codemirror/mode/javascript/javascript.js" charset="utf-8"></script>
	<script src="../online-json-diff-master/www/lib/codemirror/addon/edit/matchbrackets.js" charset="utf-8"></script>
	<script src="../online-json-diff-master/js/main.js" charset="utf-8"></script>
	</body>
</html>

grails-app/views/apiRunResult/show.gsp
<%@ page import="com.mphrx.apiAutomation.ApiRunResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'apiRunResult.label', default: 'ApiRunResult')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-apiRunResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-apiRunResult" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list apiRunResult">
			
				<g:if test="${apiRunResultInstance?.api}">
				<li class="fieldcontain">
					<span id="api-label" class="property-label"><g:message code="apiRunResult.api.label" default="Api" /></span>
					
						<span class="property-value" aria-labelledby="api-label"><g:fieldValue bean="${apiRunResultInstance}" field="api"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.apiRun}">
				<li class="fieldcontain">
					<span id="apiRun-label" class="property-label"><g:message code="apiRunResult.apiRun.label" default="Api Run" /></span>
					
						<span class="property-value" aria-labelledby="apiRun-label"><g:link controller="apiRun" action="show" id="${apiRunResultInstance?.apiRun?.id}">${apiRunResultInstance?.apiRun?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.baseResponse}">
				<li class="fieldcontain">
					<span id="baseResponse-label" class="property-label"><g:message code="apiRunResult.baseResponse.label" default="Base Response" /></span>
					
						<span class="property-value" aria-labelledby="baseResponse-label"><g:fieldValue bean="${apiRunResultInstance}" field="baseResponse"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.baseResponseCode}">
				<li class="fieldcontain">
					<span id="baseResponseCode-label" class="property-label"><g:message code="apiRunResult.baseResponseCode.label" default="Base Response Code" /></span>
					
						<span class="property-value" aria-labelledby="baseResponseCode-label"><g:fieldValue bean="${apiRunResultInstance}" field="baseResponseCode"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="apiRunResult.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${apiRunResultInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.error}">
				<li class="fieldcontain">
					<span id="error-label" class="property-label"><g:message code="apiRunResult.error.label" default="Error" /></span>
					
						<span class="property-value" aria-labelledby="error-label"><g:fieldValue bean="${apiRunResultInstance}" field="error"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="apiRunResult.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${apiRunResultInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.moduleName}">
				<li class="fieldcontain">
					<span id="moduleName-label" class="property-label"><g:message code="apiRunResult.moduleName.label" default="Module Name" /></span>
					
						<span class="property-value" aria-labelledby="moduleName-label"><g:fieldValue bean="${apiRunResultInstance}" field="moduleName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.payload}">
				<li class="fieldcontain">
					<span id="payload-label" class="property-label"><g:message code="apiRunResult.payload.label" default="Payload" /></span>
					
						<span class="property-value" aria-labelledby="payload-label"><g:fieldValue bean="${apiRunResultInstance}" field="payload"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.result}">
				<li class="fieldcontain">
					<span id="result-label" class="property-label"><g:message code="apiRunResult.result.label" default="Result" /></span>
					
						<span class="property-value" aria-labelledby="result-label"><g:fieldValue bean="${apiRunResultInstance}" field="result"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.testCaseName}">
				<li class="fieldcontain">
					<span id="testCaseName-label" class="property-label"><g:message code="apiRunResult.testCaseName.label" default="Test Case Name" /></span>
					
						<span class="property-value" aria-labelledby="testCaseName-label"><g:fieldValue bean="${apiRunResultInstance}" field="testCaseName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.testResonseCode}">
				<li class="fieldcontain">
					<span id="testResonseCode-label" class="property-label"><g:message code="apiRunResult.testResonseCode.label" default="Test Resonse Code" /></span>
					
						<span class="property-value" aria-labelledby="testResonseCode-label"><g:fieldValue bean="${apiRunResultInstance}" field="testResonseCode"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${apiRunResultInstance?.testResponse}">
				<li class="fieldcontain">
					<span id="testResponse-label" class="property-label"><g:message code="apiRunResult.testResponse.label" default="Test Response" /></span>
					
						<span class="property-value" aria-labelledby="testResponse-label"><g:fieldValue bean="${apiRunResultInstance}" field="testResponse"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:apiRunResultInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${apiRunResultInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>