grails-app/domain/com/mphrx/apiAutomation/DicrRunError.groovy
package com.mphrx.apiAutomation

import com.mongodb.BasicDBObject

class DicrRunError {

    static constraints = {
    }

    static mapping = {
        collection "dicrRunError"
    }

    static mapWith = "mongo"

    static belongsTo = [dicrRunResult:DicrRunResult]
    static embedded = ['comparisonError']

    String collectionName
    String countMismatchError
    List<ComparisonError> comparisonError
    Date dateCreated
}

grails-app/controllers/com/mphrx/apiAutomation/DicrRunErrorController.groovy
package com.mphrx.apiAutomation



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DicrRunErrorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond DicrRunError.list(params), model:[dicrRunErrorInstanceCount: DicrRunError.count()]
    }

    def show(DicrRunError dicrRunErrorInstance) {
        respond dicrRunErrorInstance
    }

    def create() {
        respond new DicrRunError(params)
    }

    @Transactional
    def save(DicrRunError dicrRunErrorInstance) {
        if (dicrRunErrorInstance == null) {
            notFound()
            return
        }

        if (dicrRunErrorInstance.hasErrors()) {
            respond dicrRunErrorInstance.errors, view:'create'
            return
        }

        dicrRunErrorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'dicrRunError.label', default: 'DicrRunError'), dicrRunErrorInstance.id])
                redirect dicrRunErrorInstance
            }
            '*' { respond dicrRunErrorInstance, [status: CREATED] }
        }
    }

    def edit(DicrRunError dicrRunErrorInstance) {
        respond dicrRunErrorInstance
    }

    @Transactional
    def update(DicrRunError dicrRunErrorInstance) {
        if (dicrRunErrorInstance == null) {
            notFound()
            return
        }

        if (dicrRunErrorInstance.hasErrors()) {
            respond dicrRunErrorInstance.errors, view:'edit'
            return
        }

        dicrRunErrorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'DicrRunError.label', default: 'DicrRunError'), dicrRunErrorInstance.id])
                redirect dicrRunErrorInstance
            }
            '*'{ respond dicrRunErrorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(DicrRunError dicrRunErrorInstance) {

        if (dicrRunErrorInstance == null) {
            notFound()
            return
        }

        dicrRunErrorInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'DicrRunError.label', default: 'DicrRunError'), dicrRunErrorInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'dicrRunError.label', default: 'DicrRunError'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/dicrRunError/_form.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunError" %>



<div class="fieldcontain ${hasErrors(bean: dicrRunErrorInstance, field: 'collectionName', 'error')} required">
	<label for="collectionName">
		<g:message code="dicrRunError.collectionName.label" default="Collection Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="collectionName" required="" value="${dicrRunErrorInstance?.collectionName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunErrorInstance, field: 'comparisonError', 'error')} ">
	<label for="comparisonError">
		<g:message code="dicrRunError.comparisonError.label" default="Comparison Error" />
		
	</label>
	

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunErrorInstance, field: 'countMismatchError', 'error')} required">
	<label for="countMismatchError">
		<g:message code="dicrRunError.countMismatchError.label" default="Count Mismatch Error" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="countMismatchError" required="" value="${dicrRunErrorInstance?.countMismatchError}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: dicrRunErrorInstance, field: 'dicrRunResults', 'error')} required">
	<label for="dicrRunResults">
		<g:message code="dicrRunError.dicrRunResults.label" default="Dicr Run Results" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="dicrRunResults" name="dicrRunResults.id" from="${com.mphrx.apiAutomation.DicrRunResult.list()}" optionKey="id" required="" value="${dicrRunErrorInstance?.dicrRunResults?.id}" class="many-to-one"/>

</div>

grails-app/views/dicrRunError/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunError.label', default: 'DicrRunError')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-dicrRunError" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-dicrRunError" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${dicrRunErrorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${dicrRunErrorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:dicrRunErrorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/dicrRunError/edit.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunError.label', default: 'DicrRunError')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-dicrRunError" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-dicrRunError" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${dicrRunErrorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${dicrRunErrorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:dicrRunErrorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${dicrRunErrorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/dicrRunError/index.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunError.label', default: 'DicrRunError')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
		<link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/lib',file: 'codemirror.css')}" charset="utf-8">
		<link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/theme',file: 'tomorrow-night.css')}" charset="utf-8">
		<link rel="stylesheet" href="${resource(dir: 'css',file: 'main.css')}" charset="utf-8">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>jQuery UI Dialog - Default functionality</title>
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<link rel="stylesheet" href="/resources/demos/style.css">
		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<style>
		.CodeMirror {
			border: 1px solid #eee;
			min-height:500px;
		}
		</style>
	</head>
	<body>
		<a href="#list-dicrRunError" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-dicrRunError" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<g:sortableColumn property="id" title="${message(code: 'dicrRunError.id.label', default: 'ID')}" />

						<g:sortableColumn property="collectionName" title="${message(code: 'dicrRunError.collectionName.label', default: 'Collection Name')}" />
					
						<g:sortableColumn property="countMismatchError" title="${message(code: 'dicrRunError.countMismatchError.label', default: 'Count Mismatch Error')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'dicrRunError.dateCreated.label', default: 'Date Created')}" />

						<g:sortableColumn property="ComparisonError" title="${message(code: 'dicrRunError.ComparisonError.label', default: 'Comparison Error')}" />

						%{--
                                                <th><g:message code="dicrRunError.dicrRunResults.label" default="Dicr Run Results" /></th>
                        --}%

%{--
						<g:sortableColumn property="lastUpdated" title="${message(code: 'dicrRunError.lastUpdated.label', default: 'Last Updated')}" />
--}%

					</tr>
				</thead>
				<tbody>

	<g:each in="${dicrRunErrorInstanceList}" status="i" var="dicrRunErrorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td>${dicrRunErrorInstance.id}</td>


						<td><g:link action="show" id="${dicrRunErrorInstance.id}">${fieldValue(bean: dicrRunErrorInstance, field: "collectionName")}</g:link></td>
					
						<td>${fieldValue(bean: dicrRunErrorInstance, field: "countMismatchError")}</td>
					
						<td><g:formatDate date="${dicrRunErrorInstance.dateCreated}" /></td>

						<td>
							<g:each in="${dicrRunErrorInstance.comparisonError}" var="comparisonErrorInstance" status="index">
								<button onclick="showErrorMessage('${URLEncoder.encode(comparisonErrorInstance.errorText,'UTF-8').replace("+", "%20")}')" value="Show Error" name="btn_${index+1}" >Show Error ${index+1} </button>
								<button onclick="showJSONDifference(${comparisonErrorInstance.baseJSON},${comparisonErrorInstance.testJSON},this)" value="Show Diff" name="btn_${index+1}" >Show Diff ${index+1}</button>
							</g:each>
						</td>


						%{--
                                                <td>${fieldValue(bean: dicrRunErrorInstance, field: "dicrRunResults")}</td>
                        --}%

%{--
						<td><g:formatDate date="${dicrRunErrorInstance.lastUpdated}" /></td>
--}%

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${dicrRunErrorInstanceCount ?: 0}" />
			</div>
		</div>

	<header id="header">

		<div class="right">
			<span id="error-message" style="display:none;">Invalid JSON</span>
		</div>
	</header>


	</div>

	<!-- The Modal -->
	<div id="myModal">


	</div>

	<div id = "jsonDiff-modal" style="width: 0px;height: 0px;">

		<div class="json-diff-input" style="width:50%; height: 100%; float:left;">
			<textarea id="json-diff-left"></textarea>
		</div>
		<div class="json-diff-input" style="width:50%; height: 100%;float:left;">
			<textarea id="json-diff-right"></textarea>
		</div>
		<div style="clear:both;"></div>
	</div>

	<script src="${resource(dir: 'www/lib/fast-json-patch/dist/',file: 'json-patch-duplex.min.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/backbone-events-standalone/',file: 'backbone-events-standalone.min.js')}" charset="utf-8"></script>

	<script src="${resource(dir: 'www/lib/codemirror/lib/',file: 'codemirror.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/codemirror/lib/util/',file: 'formatting.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/codemirror/mode/javascript/',file: 'javascript.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'www/lib/codemirror/addon/edit/',file: 'matchbrackets.js')}" charset="utf-8"></script>
	<script src="${resource(dir: 'js/',file: 'main.js')}" charset="utf-8"></script>

	<script type="text/javascript">
		function showJSONDifference(json1,json2,element){
			var cmLeft = $('.CodeMirror')[0].CodeMirror;
			var cmRight = $('.CodeMirror')[1].CodeMirror;

			cmLeft.setValue("");
			cmRight.setValue("");
			cmLeft.setValue(JSON.stringify(json1,null,4));
			cmRight.setValue(JSON.stringify(json2,null,4));

			$('#jsonDiff-modal').removeAttr('style');
			$('#jsonDiff-modal').dialog( {
				width: "90%",
				maxWidth: "768px",
				height:'580'
			});
			cmLeft.focus();
			cmLeft.setCursor({line: 0, ch: 1});
			cmLeft;
		}

		function showErrorMessage(error) {
			$( "#myModal" ).html("<pre></pre>")
			$( "#myModal pre" ).text(decodeURIComponent(error));
			$( "#myModal" ).dialog({width: "90%",
				maxWidth: "768px",
				height:'580'});
		}

	</script>

	</body>
</html>

grails-app/views/dicrRunError/show.gsp
<%@ page import="com.mphrx.apiAutomation.DicrRunError" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dicrRunError.label', default: 'DicrRunError')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-dicrRunError" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-dicrRunError" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list dicrRunError">
			
				<g:if test="${dicrRunErrorInstance?.collectionName}">
				<li class="fieldcontain">
					<span id="collectionName-label" class="property-label"><g:message code="dicrRunError.collectionName.label" default="Collection Name" /></span>
					
						<span class="property-value" aria-labelledby="collectionName-label"><g:fieldValue bean="${dicrRunErrorInstance}" field="collectionName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${dicrRunErrorInstance?.comparisonError}">
				<li class="fieldcontain">
					<span id="comparisonError-label" class="property-label"><g:message code="dicrRunError.comparisonError.label" default="Comparison Error" /></span>
					
						<span class="property-value" aria-labelledby="comparisonError-label"><g:fieldValue bean="${dicrRunErrorInstance}" field="comparisonError"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${dicrRunErrorInstance?.countMismatchError}">
				<li class="fieldcontain">
					<span id="countMismatchError-label" class="property-label"><g:message code="dicrRunError.countMismatchError.label" default="Count Mismatch Error" /></span>
					
						<span class="property-value" aria-labelledby="countMismatchError-label"><g:fieldValue bean="${dicrRunErrorInstance}" field="countMismatchError"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${dicrRunErrorInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="dicrRunError.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${dicrRunErrorInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${dicrRunErrorInstance?.dicrRunResults}">
				<li class="fieldcontain">
					<span id="dicrRunResults-label" class="property-label"><g:message code="dicrRunError.dicrRunResults.label" default="Dicr Run Results" /></span>
					
						<span class="property-value" aria-labelledby="dicrRunResults-label"><g:link controller="dicrRunResult" action="show" id="${dicrRunErrorInstance?.dicrRunResults?.id}">${dicrRunErrorInstance?.dicrRunResults?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${dicrRunErrorInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="dicrRunError.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${dicrRunErrorInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:dicrRunErrorInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${dicrRunErrorInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/dicrRunError/view.gsp
<%--
  Created by IntelliJ IDEA.
  User: amitsandhal
  Date: 11/30/2016
  Time: 8:01 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'dicrRunError.label', default: 'DicrRunError')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
    <link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/lib',file: 'codemirror.css')}" charset="utf-8">
    <link rel="stylesheet" href="${resource(dir: 'www/lib/codemirror/theme',file: 'tomorrow-night.css')}" charset="utf-8">
    <link rel="stylesheet" href="${resource(dir: 'css',file: 'main.css')}" charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>jQuery UI Dialog - Default functionality</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>
    .CodeMirror {
        border: 1px solid #eee;
        min-height:500px;
    }
    </style>
</head>

<body>
<a href="#list-dicrRunError" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
    </ul>
</div>
<div id="list-dicrRunError" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="id" title="${message(code: 'dicrRunError.id.label', default: 'ID')}" />

            <g:sortableColumn property="collectionName" title="${message(code: 'dicrRunError.collectionName.label', default: 'Collection Name')}" />

            <g:sortableColumn property="countMismatchError" title="${message(code: 'dicrRunError.countMismatchError.label', default: 'Count Mismatch Error')}" />

            <g:sortableColumn property="dateCreated" title="${message(code: 'dicrRunError.dateCreated.label', default: 'Date Created')}" />

            <g:sortableColumn property="ComparisonError" title="${message(code: 'dicrRunError.ComparisonError.label', default: 'Comparison Error')}" />

            %{--
                                    <th><g:message code="dicrRunError.dicrRunResults.label" default="Dicr Run Results" /></th>
            --}%

            %{--
                                    <g:sortableColumn property="lastUpdated" title="${message(code: 'dicrRunError.lastUpdated.label', default: 'Last Updated')}" />
            --}%

        </tr>
        </thead>
        <tbody>

        <g:each in="${dicrRunErrorInstanceList}" status="i" var="dicrRunErrorInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td>${dicrRunErrorInstance.id}</td>


                <td><g:link action="show" id="${dicrRunErrorInstance.id}">${fieldValue(bean: dicrRunErrorInstance, field: "collectionName")}</g:link></td>

                <td>${fieldValue(bean: dicrRunErrorInstance, field: "countMismatchError")}</td>

                <td><g:formatDate date="${dicrRunErrorInstance.dateCreated}" /></td>

                <td>
                    <g:each in="${dicrRunErrorInstance.comparisonError}" var="comparisonErrorInstance" status="index">
                        <button onclick="showErrorMessage('${URLEncoder.encode(comparisonErrorInstance.errorText,'UTF-8').replace("+", "%20")}')" value="Show Error" name="btn_${index+1}" >Show Error ${index+1} </button>
                        <button onclick="showJSONDifference(${comparisonErrorInstance.baseJSON},${comparisonErrorInstance.testJSON},this)" value="Show Diff" name="btn_${index+1}" >Show Diff ${index+1}</button>
                    </g:each>
                </td>


                %{--
                                        <td>${fieldValue(bean: dicrRunErrorInstance, field: "dicrRunResults")}</td>
                --}%

                %{--
                                        <td><g:formatDate date="${dicrRunErrorInstance.lastUpdated}" /></td>
                --}%

            </tr>
        </g:each>
        </tbody>
    </table>
    <div class="pagination">
        <g:paginate total="${dicrRunErrorInstanceCount ?: 0}" />
    </div>
</div>

<header id="header">

    <div class="right">
        <span id="error-message" style="display:none;">Invalid JSON</span>
    </div>
</header>


</div>

<!-- The Modal -->
<div id="myModal">


</div>

<div id = "jsonDiff-modal" style="width: 0px;height: 0px;">

    <div class="json-diff-input" style="width:50%; height: 100%; float:left;">
        <textarea id="json-diff-left"></textarea>
    </div>
    <div class="json-diff-input" style="width:50%; height: 100%;float:left;">
        <textarea id="json-diff-right"></textarea>
    </div>
    <div style="clear:both;"></div>
</div>

<script src="${resource(dir: 'www/lib/fast-json-patch/dist/',file: 'json-patch-duplex.min.js')}" charset="utf-8"></script>
<script src="${resource(dir: 'www/lib/backbone-events-standalone/',file: 'backbone-events-standalone.min.js')}" charset="utf-8"></script>

<script src="${resource(dir: 'www/lib/codemirror/lib/',file: 'codemirror.js')}" charset="utf-8"></script>
<script src="${resource(dir: 'www/lib/codemirror/lib/util/',file: 'formatting.js')}" charset="utf-8"></script>
<script src="${resource(dir: 'www/lib/codemirror/mode/javascript/',file: 'javascript.js')}" charset="utf-8"></script>
<script src="${resource(dir: 'www/lib/codemirror/addon/edit/',file: 'matchbrackets.js')}" charset="utf-8"></script>
<script src="${resource(dir: 'js/',file: 'main.js')}" charset="utf-8"></script>

<script type="text/javascript">
    function showJSONDifference(json1,json2,element){
        var cmLeft = $('.CodeMirror')[0].CodeMirror;
        var cmRight = $('.CodeMirror')[1].CodeMirror;

        cmLeft.setValue("");
        cmRight.setValue("");
        cmLeft.setValue(JSON.stringify(json1,null,4));
        cmRight.setValue(JSON.stringify(json2,null,4));

        $('#jsonDiff-modal').removeAttr('style');
        $('#jsonDiff-modal').dialog( {
            width: "90%",
            maxWidth: "768px",
            height:'580'
        });
        cmLeft.focus();
        cmLeft.setCursor({line: 0, ch: 1});
        cmLeft;
    }

    function showErrorMessage(error) {
        $( "#myModal" ).html("<pre></pre>")
        $( "#myModal pre" ).text(decodeURIComponent(error));
        $( "#myModal" ).dialog({width: "90%",
            maxWidth: "768px",
            height:'580'});
    }

</script>
</body>
</html>